version: '3.8'
services:
 app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: cms_container
    command: ["sh", "./start.sh"]
    env_file:
      - .env
    depends_on:
      - postgres_db

 postgres_db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:

  