# Generated by Django 4.2.9 on 2024-02-12 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('policy_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('health', 'Health'), ('life', 'Life'), ('auto', 'Auto')], max_length=100)),
                ('lumpsum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.UUIDField()),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('B', 'Rejected'), ('C', 'Initiated')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('res_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(default='--')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
