# Generated by Django 4.2.9 on 2024-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
